### ISSUE TITLE
a problem about using Tabulated Reaction Rates instead of Reaclib format

### ISSUE THREAD

**Issue by sameulleaf** [nuc-astro/WinNet#9]
Hi.
I calculated forward reaction rate with talys and successfully obtain the 30 reaction rates at 10^−4 to 10 GK.  I noticed that the default reaction rates are stored in the Reaclib format with 7 fitting parameters.  I  know that the reaction rate with tabulated form has higher priority than the Reaclib format.   

Would you please tell me the place where I should place my 30 tabulated rates ?  since i didn't find similar tabulated format file in data folder.

Best regards.

**Comment by Mreichert91** [comment]
Hi,
Sorry for my late reply. I'm often overlooking this Issue forum. If you want you can write a e-mail next time to me directly.
The "Example_AGB_nishimura" uses tabulated rates. If it is in the correct form, you can use them with the following two parameters:
use_tabulated_rates  = yes
tabulated_rates_file = @WINNET@/data/Example_data/Example_AGB_nishimura/tab_rates.dat

An example of tabulated rates is given at this [path](https://github.com/nuc-astro/WinNet/blob/master/data/Example_data/Example_AGB_nishimura/tab_rates.dat). The format is a mixture of the reaclib format and the tabulation below. So you need the reaclib chapters and the line for the reactions. Another example is also given in the [documentation](https://nuc-astro.github.io/WinNet/parameters.html#tabulated_rates_file). Note that when you give the reaction the "v" flag for reverse rate, the factor including the partition functions is multiplied to the rate by WinNet (basically the second and third brackets in Equation 21 in [Reichert et al 2023](https://ui.adsabs.harvard.edu/abs/2023ApJS..268...66R/abstract)). If talys did this already, dont put the "v" flag as you would do things twice.
Best,
Moritz
